name: csi-s3 images
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build s3 driver
        id: docker_build_s3_driver
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./cmd/s3driver/Dockerfile
          push: true
          tags: latest

      - name: build s3 driver full
        id: docker_build_s3_full
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./cmd/s3driver/Dockerfile.full
          push: true
          tags: full
